### ISSUE TITLE
Race Condition with runSetupWizard=false on debian based systems

### ISSUE THREAD

**Issue by DexterTheDragon** [geerlingguy/ansible-role-jenkins#116]
On debian based systems, the default behavior is to start a service immediately after installing it. This creates a race condition with the "runSetupWizard=false" setting and how this role handles the admin user. I believe this is the cause of the problem discussed in issue #79. I end up seeing two different behaviors when I'm using a low powered VirtualBox VM vs a higher powered EC2 instance. 

When using a default config like:
```yaml
jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_repo_url: deb http://pkg.jenkins-ci.org/debian-stable binary/
jenkins_repo_key_url: http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
jenkins_plugins: 
  - workflow-aggregator
```
When I run this in a VirtualBox VM it installs Jenkins and the plugins just fine. But when I run it on EC2 it triggers a race condition. In the following I'll paste the output from ansible and insert markers to reference what is happening.
```
TASK [geerlingguy.jenkins : Add Jenkins apt repository key.] *******************
changed: [jenkins]

TASK [geerlingguy.jenkins : Add Jenkins apt repository.] ***********************
changed: [jenkins]

TASK [geerlingguy.jenkins : Download specific Jenkins version.] ****************
skipping: [jenkins]

TASK [geerlingguy.jenkins : Check if we downloaded a specific version of Jenkins.] ***
ok: [jenkins]

TASK [geerlingguy.jenkins : Install our specific version of Jenkins.] **********
skipping: [jenkins]

TASK [geerlingguy.jenkins : Validate Jenkins is installed and register package name.] ***  [1]
changed: [jenkins]

TASK [geerlingguy.jenkins : Install Jenkins from repository.] ****************** 
ok: [jenkins]

TASK [geerlingguy.jenkins : Modify variables in init file] *********************           [2]
changed: [jenkins] => (item={u'option': u'JENKINS_ARGS', u'value': u'--prefix='})
changed: [jenkins] => (item={u'option': u'JAVA_ARGS', u'value': u'-Djenkins.install.runSetupWizard=false'})

TASK [geerlingguy.jenkins : Set the Jenkins home directory] ********************
changed: [jenkins]

TASK [geerlingguy.jenkins : Immediately restart Jenkins on init config changes.] ***       [3]
changed: [jenkins]

TASK [geerlingguy.jenkins : Set HTTP port in Jenkins config.] ******************
ok: [jenkins]

TASK [geerlingguy.jenkins : Create custom init scripts directory.] *************
changed: [jenkins]

RUNNING HANDLER [geerlingguy.jenkins : configure default users] ****************           [4]
changed: [jenkins]

TASK [geerlingguy.jenkins : Immediately restart Jenkins on http or user changes.] ***
changed: [jenkins]
```
[1] At this point Jenkins has installed and has fully booted. It booted with the default config meaning it ran the setup wizard and has switched to using the basic Jenkins user database and has created an "admin" user.
[2] The role now adds the `-Djenkins.install.runSetupWizard=false` setting to `/etc/default/jenkins`.
[3] Jenkins is restarted.
[4] The role attempts to create the admin user but the security system has already been turned on so it skips doing anything.

After that, plugin installation fails due to the username/password not being correct.

On the flip side of this if I use a config like:
```yaml
jenkins_admin_username: admin
jenkins_admin_password: ""
jenkins_admin_password_file: "/var/lib/jenkins/secrets/initialAdminPassword"
jenkins_java_options: ""
jenkins_plugins: 
  - workflow-aggregator
```
It works on EC2 because Jenkins boots up, runs the setup wizard creating the admin user and the password file. Then when it's ready to install plugins it can use the password file just fine. However when trying this on VirtualBox it seems to do something like Jenkins starts booting, it begins running the setup wizard and manages to create the admin user but before it can write the password file ansible restarts Jenkins. Then the password file isn't present so plugins aren't installed and you can't login cause you don't know the admin password.

I'm unsure how to fix this. I looked at the jenkins puppet module, which is a core jenkins project, and it does the same thing. It installs Jenkins, adds `-Djenkins.install.runSetupWizard=false` to `/etc/default/jenkins`, then issues a restart. Depending on how powerful your machine is you can either end up with Jenkins running with no security or Jenkins running with basic security enabled.

One option would be to create `/etc/default/jenkins` before installing the package. This would get the  `-Djenkins.install.runSetupWizard=false` setting into place before Jenkins ever has the chance to start. It would require the role to manage the full file instead of just adding a couple of lines to it, so maybe not ideal.

Debian provides a mechanism to control the auto starting of services but I find it to be a bit janky. If an executable exists at `/usr/sbin/policy-rc.d` it will be called and if it returns an exit code of 101 the action won't be run. I'm currently using this method to ensure things work for me. I've added these tasks to my playbook:
```yaml
  pre_tasks:                                                                                                                                         
    - name: Install policy-rc.d script                                                                                                               
      copy:                                                                                                                                          
        dest: /usr/sbin/policy-rc.d                                                                                                                  
        content: |                                                                                                                                   
          #!/bin/bash                                                                                                                                                                                                              
          exit 101                                                                                                                                                                                                                                                                    
        mode: 0755
  post_tasks:                                                                                                                                        
    - name: Remove policy-rc.d script                                                                                                                
      file:                                                                                                                                          
        path: /usr/sbin/policy-rc.d                                                                                                                  
        state: absent
```
This prevents apt from auto starting the service. When explicating starting the service it doesn't call `/usr/sbin/policy-rc.d` so everything works fine. Docker does the same thing so problems don't occur when building images https://github.com/docker/docker/blob/4534dcd494979ea89d8243002fb478857e25032d/contrib/mkimage/debootstrap#L64-L74 This works for me but I don't know if it's a viable universal solution. There may be a slim chance where a user has a custom `/usr/sbin/policy-rc.d` script already so creating then removing the script during the role might not work. This could possibly be solved by checking first for the existence of the file and erroring out in that case.

A final option could be to change the `basic-security.groovy` script and have the role just always enable the `FullControlOnceLoggedInAuthorizationStrategy` strategy and always create the user account. This might require adding a variable to the role to explicitly have it manage security that way people with preexisting security configurations can still use the role.
