### ISSUE TITLE
Role assumes become: true

### ISSUE THREAD

**Issue by herebebogans** [geerlingguy/ansible-role-jenkins#155]
The role seems to assume that it will be run as root but this is not stated anywhere. Examples tasks requiring privelege include yum package installs.

Should the sample playbook in the Readme be updated with?

```
- hosts: ci-server
  vars:
    jenkins_hostname: jenkins.example.com
  roles:
    - geerlingguy.jenkins
      become:true
```
