### ISSUE TITLE
Ansible 2.4 compability

### ISSUE THREAD

**Issue by sebastianludwig** [geerlingguy/ansible-role-jenkins#174]
I'm using this role as follows:

```yaml
- name: Setup Jenkins
  include_role:
    name: geerlingguy.jenkins
```

This leads to the following error:
```
[...]
TASK [geerlingguy.java : Include OS-specific variables.] ***********************
ok: [log-server]

TASK [geerlingguy.java : Include OS-specific variables for Fedora.] ************
skipping: [log-server]

TASK [geerlingguy.java : Include version-specific variables for Ubuntu.] *******
ok: [log-server]

TASK [geerlingguy.java : Define java_packages.] ********************************
ok: [log-server]

TASK [geerlingguy.java : include_tasks] ****************************************
skipping: [log-server]

TASK [geerlingguy.java : include_tasks] ****************************************
included: /Users/[...]/ansible/galaxy_roles/geerlingguy.jenkins/tasks/setup-Debian.yml for log-server

TASK [geerlingguy.java : Ensure dependencies are installed.] *******************
ok: [log-server]

TASK [geerlingguy.java : Add Jenkins apt repository key.] **********************
fatal: [log-server]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'jenkins_repo_key_url' is undefined\n\nThe error appears to have been in '/Users/[...]/ansible/galaxy_roles/geerlingguy.jenkins/tasks/setup-Debian.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add Jenkins apt repository key.\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'jenkins_repo_key_url' is undefined"}
	to retry, use: --limit @/Users/[...]/ansible/log-server.retry
```

So geerlingguy.java includes `setup-Debian` from geerlingguy.jenkins. I've tried the changes of geerlingguy/ansible-role-java#56 which does not help. Using `import_tasks` instead of `include_tasks` _does_ help. Using `import_role` instead of `include_role` in my playbook doesn't work either. Also ansible/ansible#29052 might be related. 

I was very unsure where to open this issue, so it's probably wrong here, but it's the "top most" component used: geerlingguy.java doesn't have the issue if used isolated and I'm not sure if it's a general Ansible bug - any pointers to the right repository appreciated!

**Comment by sebastianludwig** [comment]
To be explicit: The problem is that `geerlingguy.java` includes its `setup-Debian.yml` but the `setup-Debian.yml` from `geerlingguy.jenkins` is included.

**Comment by geerlingguy** [comment]
Strange... this seems like it would be a bug with Ansible's changes to includes, maybe—the new include/import options are preferred now, but it shouldn't break backwards compatibility since there are _tons_ of roles that do a similar thing.

**Comment by caphrim007** [comment]
I get the same error

**Comment by caphrim007** [comment]
it seems that it occurs only when this role is used in include_role. the same does not happen when you name the role in the `roles` list. So I wonder if it's including the role's tasks in the context of the other role.

**Comment by vrosales** [comment]
I have the same issue using "include_role"

**Comment by ham-360** [comment]
Same issue for me

**Comment by ham-360** [comment]
Just thought i'd share some minor observation which doesn't help anyone.
I tried to use the 'vars_from' property of the include_role task as below.
```yaml
- include_role:
    name: geerlingguy.jenkins
    vars_from: <var-file>
```

If I specify a value which doesn't exist, the play hangs as it can't find the specified file.  If I specify 'Debian' (in my case), the role proceeds as it can find the file, but fails with the same error.  i.e. even though ive explicitly pointed ansible to the right file, it still doesn't think it has the variable it needs.

**Comment by fubarhouse** [comment]
I had this over the weekend, it seems it is a regression between the current latest version and Ansible 2.4.0.0.

By changing to version 2.4.0.0, I was able to run the play as expected.

**Comment by marcindulak** [comment]
I've run successfully the upcoming https://github.com/ansible/ansible/tree/v2.5.0b1 on CentOS7 against https://github.com/geerlingguy/ansible-role-jenkins/commit/9e84d02cde7f87310b2b2815fcb62bb930449dcb using include_role, so maybe 2.5 will solve the problem

```
- hosts: all
  gather_facts: true
  become: yes

  tasks:

  - name: install java
    include_role:
      name: geerlingguy.java
      private: yes
    vars:
      - __java_packages: ['java-1.8.0-openjdk-1.8.0.161']

  - name: install jenkins master
    include_role:
      name: geerlingguy.jenkins
      private: yes
    vars:
      - jenkins_version: "2.110"
```
