### ISSUE TITLE
"Get Jenkins admin password from file." fails

### ISSUE THREAD

**Issue by angel-manuel** [geerlingguy/ansible-role-jenkins#182]
While installing over docker image centos:7

```
    docker-centos: TASK [geerlingguy.jenkins : Get Jenkins admin password from file.] *************
    docker-centos: fatal: [default]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
```

My playbook is

```yml
---

- hosts: all
  roles:
    - role: geerlingguy.java
      java_packages:
        - java-1.8.0-openjdk
    - role: geerlingguy.jenkins
      no_log: false #Also fails without this
      jenkins_package_state: latest
      jenkins_plugins_state: latest
      jenkins_http_port: 8080
      jenkins_admin_username: "admin"
      jenkins_admin_password_file: "../default-jenkins-password.txt"
      jenkins_plugins:
        - blueocean
        - git
        - pipeline-model-definition
      become: true
```
