### ISSUE TITLE
Failing on 'Wait for Jenkins to start up before proceeding.' when trying to install jenkins locally on vagrant machine.

### ISSUE THREAD

**Issue by jakelacey2012** [geerlingguy/ansible-role-jenkins#185]
I'm new to Ansible and I've been following this tutorial http://codeheaven.io/an-introduction-to-ansible everything seems to install fine up this task 'Wait for Jenkins to start up before proceeding.'

I've created this repo https://github.com/jakelacey2012/ansible-jenkins

but here are some highlighted bits.

```
Vagrant.configure(2) do |config|
       	config.vm.box = "centos/7"
       	config.vm.network "forwarded_port", guest: 8080, host: 8080
end
```

```
---
- name: Configure CI server
  hosts: ci-server
  sudo: True
  vars:
    jenkins_hostname: localhost
    jenkins_connection_retries: 60
  roles:
    - git
    - geerlingguy.java
    - geerlingguy.jenkins
```

Is there something I'm missing?
