### ISSUE TITLE
 TASK [Ensure Jenkins is installed.] failed

### ISSUE THREAD

**Issue by willis7** [geerlingguy/ansible-role-jenkins#204]
Log:

```
TASK [geerlingguy.jenkins : Ensure Jenkins is installed.] **********************
fatal: [master]: FAILED! => {"cache_update_time": 1524134908, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'jenkins'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following extra packages will be installed:\n  daemon\nThe following NEW packages will be installed:\n  daemon jenkins\n0 upgraded, 2 newly installed, 0 to remove and 33 not upgraded.\nNeed to get 73.7 MB of archives.\nAfter this operation, 75.0 MB of additional disk space will be used.\nGet:1 http://httpredir.debian.org/debian/ jessie/main daemon amd64 0.6.4-1 [97.4 kB]\nGet:2 https://pkg.jenkins.io/debian/ binary/ jenkins 2.117 [73.6 MB]\nFetched 73.7 MB in 49s (1477 kB/s)\nSelecting previously unselected package daemon.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 33698 files and directories currently installed.)\r\nPreparing to unpack .../daemon_0.6.4-1_amd64.deb ...\r\nUnpacking daemon (0.6.4-1) ...\r\nSelecting previously unselected package jenkins.\r\nPreparing to unpack .../archives/jenkins_2.117_all.deb ...\r\nUnpacking jenkins (2.117) ...\r\nProcessing triggers for man-db (2.7.0.2-5) ...\r\nProcessing triggers for systemd (215-17+deb8u7) ...\r\nSetting up daemon (0.6.4-1) ...\r\nSetting up jenkins (2.117) ...\r\nJob for jenkins.service failed. See 'systemctl status jenkins.service' and 'journalctl -xn' for details.\r\ninvoke-rc.d: initscript jenkins, action \"start\" failed.\r\ndpkg: error processing package jenkins (--configure):\r\n subprocess installed post-installation script returned error exit status 1\r\nProcessing triggers for systemd (215-17+deb8u7) ...\r\nErrors were encountered while processing:\r\n jenkins\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following extra packages will be installed:", "  daemon", "The following NEW packages will be installed:", "  daemon jenkins", "0 upgraded, 2 newly installed, 0 to remove and 33 not upgraded.", "Need to get 73.7 MB of archives.", "After this operation, 75.0 MB of additional disk space will be used.", "Get:1 http://httpredir.debian.org/debian/ jessie/main daemon amd64 0.6.4-1 [97.4 kB]", "Get:2 https://pkg.jenkins.io/debian/ binary/ jenkins 2.117 [73.6 MB]", "Fetched 73.7 MB in 49s (1477 kB/s)", "Selecting previously unselected package daemon.", "(Reading database ... ", "(Reading database ... 5%", "(Reading database ... 10%", "(Reading database ... 15%", "(Reading database ... 20%", "(Reading database ... 25%", "(Reading database ... 30%", "(Reading database ... 35%", "(Reading database ... 40%", "(Reading database ... 45%", "(Reading database ... 50%", "(Reading database ... 55%", "(Reading database ... 60%", "(Reading database ... 65%", "(Reading database ... 70%", "(Reading database ... 75%", "(Reading database ... 80%", "(Reading database ... 85%", "(Reading database ... 90%", "(Reading database ... 95%", "(Reading database ... 100%", "(Reading database ... 33698 files and directories currently installed.)", "Preparing to unpack .../daemon_0.6.4-1_amd64.deb ...", "Unpacking daemon (0.6.4-1) ...", "Selecting previously unselected package jenkins.", "Preparing to unpack .../archives/jenkins_2.117_all.deb ...", "Unpacking jenkins (2.117) ...", "Processing triggers for man-db (2.7.0.2-5) ...", "Processing triggers for systemd (215-17+deb8u7) ...", "Setting up daemon (0.6.4-1) ...", "Setting up jenkins (2.117) ...", "Job for jenkins.service failed. See 'systemctl status jenkins.service' and 'journalctl -xn' for details.", "invoke-rc.d: initscript jenkins, action \"start\" failed.", "dpkg: error processing package jenkins (--configure):", " subprocess installed post-installation script returned error exit status 1", "Processing triggers for systemd (215-17+deb8u7) ...", "Errors were encountered while processing:", " jenkins"]}
	to retry, use: --limit @/Users/sionix/Code/ons/jenkins-docker-slaves/provision/ansible/jenkins-master-playbook.retry

PLAY RECAP *********************************************************************
master                     : ok=14   changed=6    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Unfortunately, checking `systemctl` and `journalctl` adds no value.

```
$ systemctl status jenkins
jenkins.service - LSB: Start Jenkins at boot time
   Loaded: loaded (/etc/init.d/jenkins)
   Active: failed (Result: exit-code) since Thu 2018-04-19 10:49:21 GMT; 3min 20s ago
```
vagrant host: `debian/jessie64`

**Comment by willis7** [comment]
Missed out `sudo` for journal

```
$ sudo journalctl -u jenkins
-- Logs begin at Thu 2018-04-19 10:46:22 GMT, end at Thu 2018-04-19 11:21:26 GMT. --
Apr 19 10:49:21 master01 systemd[1]: Starting LSB: Start Jenkins at boot time...
Apr 19 10:49:21 master01 jenkins[10359]: Found an incorrect Java version
Apr 19 10:49:21 master01 jenkins[10359]: Java version found:
Apr 19 10:49:21 master01 jenkins[10359]: java version "1.7.0_171"
Apr 19 10:49:21 master01 jenkins[10359]: OpenJDK Runtime Environment (IcedTea 2.6.13) (7u171-2.6.13-1
Apr 19 10:49:21 master01 jenkins[10359]: OpenJDK 64-Bit Server VM (build 24.171-b02, mixed mode)
Apr 19 10:49:21 master01 jenkins[10359]: Aborting
Apr 19 10:49:21 master01 systemd[1]: jenkins.service: control process exited, code=exited status=1
Apr 19 10:49:21 master01 systemd[1]: Failed to start LSB: Start Jenkins at boot time.
Apr 19 10:49:21 master01 systemd[1]: Unit jenkins.service entered failed state.
Apr 19 11:21:10 master01 systemd[1]: Starting LSB: Start Jenkins at boot time...
Apr 19 11:21:10 master01 jenkins[10445]: Found an incorrect Java version
Apr 19 11:21:10 master01 jenkins[10445]: Java version found:
Apr 19 11:21:10 master01 jenkins[10445]: java version "1.7.0_171"
Apr 19 11:21:10 master01 jenkins[10445]: OpenJDK Runtime Environment (IcedTea 2.6.13) (7u171-2.6.13-1
Apr 19 11:21:10 master01 jenkins[10445]: OpenJDK 64-Bit Server VM (build 24.171-b02, mixed mode)
Apr 19 11:21:10 master01 jenkins[10445]: Aborting
Apr 19 11:21:10 master01 systemd[1]: jenkins.service: control process exited, code=exited status=1
Apr 19 11:21:10 master01 systemd[1]: Failed to start LSB: Start Jenkins at boot time.
Apr 19 11:21:10 master01 systemd[1]: Unit jenkins.service entered failed state.
```

Thats an easy fix.

**Comment by cbastienbaron** [comment]
same here on debian jessie 

```log
May  7 16:09:35 sphynx systemd[1]: Starting LSB: Start Jenkins at boot time...
May  7 16:09:35 sphynx jenkins[32711]: Found an incorrect Java version
May  7 16:09:35 sphynx jenkins[32711]: Java version found:
May  7 16:09:35 sphynx jenkins[32711]: java version "1.7.0_201"
May  7 16:09:35 sphynx jenkins[32711]: OpenJDK Runtime Environment (IcedTea 2.6.17) (7u211-2.6.17-1~deb8u1)
May  7 16:09:35 sphynx jenkins[32711]: OpenJDK 64-Bit Server VM (build 24.201-b00, mixed mode)
May  7 16:09:35 sphynx jenkins[32711]: Aborting
```

**Comment by cbastienbaron** [comment]
on documentation we can specify java version : 
```yaml
  roles:
    - common
    - dev-sec.os-hardening
    - role: geerlingguy.java
      become: yes
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
    - role: geerlingguy.jenkins
      become: yes
```

**Comment by cbastienbaron** [comment]
java8 has been removed from openjdk-r/ppa, default java version is 11 but https://github.com/geerlingguy/ansible-role-jenkins need to have java 8 .... :sob:

**Comment by cbastienbaron** [comment]
to install java 11 and jenkins 2.176 

```yaml
---
- hosts: apt-servers
  remote_user: root
  tasks:
    - name: debian | ensure the apt repository key is present
      apt_key:
        id="EA8CACC073C3DB2A"
        keyserver=keyserver.ubuntu.com
        state=present
      become: yes

    - name: debian | ensure the apt repository is present
      apt_repository:
        repo="deb http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic main"
        update_cache=yes
        state=present
      become: yes

    - name: debian | set license as accepted
      debconf:
        name="oracle-java11-installer"
        question="shared/accepted-oracle-license-v1-2"
        value='true'
        vtype='select'
      become: yes

    - name: debian | ensure Java is installed
      apt:
        name="oracle-java11-installer"
        state=latest
        cache_valid_time=3600
        update_cache=yes
      become: yes

    - name: debian | set Java version as default
      apt:
        name="oracle-java11-set-default"
        state=latest
      become: yes

- hosts: apt-servers
  remote_user: root
  roles:
    - common
#    - dev-sec.os-hardening
    - role: geerlingguy.jenkins
      become: yes
```
