### ISSUE TITLE
Plugin install is not including dependencies 

### ISSUE THREAD

**Issue by DevBOFH** [geerlingguy/ansible-role-jenkins#224]
During the plugin install, dependencies are not being installed. The strictly defined plugins are being installed just fine however. I'm hoping that I'm just missing something here.

From my `base.yml`
```
vars:
    jenkins_hostname: localhost
    jenkins_package_state: latest
    jenkins_plugins_install_dependencies: yes
    jenkins_plugins_state: latest
    jenkins_plugins: [greenballs, ghprb, workflow-aggregator, aws-codebuild, pipeline-aws, aws-cloudwatch-logs-publisher, aws-lambda, snsnotify, blueocean, docker-workflow, slack, global-slack-notifier]
```

From the Ansible build output:
```
    amazon-ebs: TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
    amazon-ebs: changed: [default] => (item=greenballs)
    amazon-ebs: changed: [default] => (item=ghprb)
    amazon-ebs: changed: [default] => (item=workflow-aggregator)
    amazon-ebs: changed: [default] => (item=aws-codebuild)
    amazon-ebs: changed: [default] => (item=pipeline-aws)
    amazon-ebs: changed: [default] => (item=aws-cloudwatch-logs-publisher)
    amazon-ebs: changed: [default] => (item=aws-lambda)
    amazon-ebs: changed: [default] => (item=snsnotify)
    amazon-ebs: changed: [default] => (item=blueocean)
    amazon-ebs: changed: [default] => (item=docker-workflow)
    amazon-ebs: changed: [default] => (item=slack)
    amazon-ebs: changed: [default] => (item=global-slack-notifier)
    amazon-ebs:
    amazon-ebs: TASK [geerlingguy.jenkins : Install Jenkins plugins using token.] **************
    amazon-ebs: skipping: [default] => (item=greenballs)
    amazon-ebs: skipping: [default] => (item=ghprb)
    amazon-ebs: skipping: [default] => (item=workflow-aggregator)
    amazon-ebs: skipping: [default] => (item=aws-codebuild)
    amazon-ebs: skipping: [default] => (item=pipeline-aws)
    amazon-ebs: skipping: [default] => (item=aws-cloudwatch-logs-publisher)
    amazon-ebs: skipping: [default] => (item=aws-lambda)
    amazon-ebs: skipping: [default] => (item=snsnotify)
    amazon-ebs: skipping: [default] => (item=blueocean)
    amazon-ebs: skipping: [default] => (item=docker-workflow)
    amazon-ebs: skipping: [default] => (item=slack)
    amazon-ebs: skipping: [default] => (item=global-slack-notifier)
    amazon-ebs:
```

Build process is using Packer version 1.2.4 with Ansible version 2.5.4 to bake an AMI from this role.
