### ISSUE TITLE
Doesn't work out of the boox - Java role needs to be root

### ISSUE THREAD

**Issue by g1ps** [geerlingguy/ansible-role-jenkins#229]
The role didn't work for me using the sample playbook shown on the readme page. It needs either
```
  roles:
    - role: geerlingguy.java
      become: yes
    - role: geerlingguy.jenkins
      become: yes
```
or
```
- hosts: all
  become: yes
```
in order to work as the Java role fails with a message that you need to be root to run it, otherwise.

Thanks.
