### ISSUE TITLE
Auto login

### ISSUE THREAD

**Issue by fdvalero** [geerlingguy/ansible-role-jenkins#230]
I like the way that you build/write the playbooks.
But I have a question, why when I login to the jenkins UI it does not ask me for user/password

Regards

**Comment by geerlingguy** [comment]
Jenkins, sadly, by default does not require a user to log in to see the dashboard and some parts of the Jenkins UI. I usually add plugins like `role-strategy` and configure Jenkins with different user roles and don't allow the anonymous user to do anything (only logged in users get any kind of access.

Please see https://wiki.jenkins.io/display/JENKINS/Securing+Jenkins for more info.

**Comment by marcoklein** [comment]
Had the same issue and fixed it by disabling anonymous access through an Ansible task:
```
- name: Deny anonymous read access
  lineinfile:
    path: ~/config.xml
    line: "<denyAnonymousReadAccess>true</denyAnonymousReadAccess>"
    regexp: "<denyAnonymousReadAccess>"
  become: true
  become_user: jenkins
  become_method: sudo
  notify: RESTART_JENKINS
```
