### ISSUE TITLE
Install Jenkins plugins using password is not working

### ISSUE THREAD

**Issue by rluisr** [geerlingguy/ansible-role-jenkins#234]
The `Install jenkins plugins using password` tasks is successfully but there are no plugins into `installed plugins` via Web GUI.

```
vars:
    jenkins_hostname: "localhost"
    jenkins_home: "/var/lib/jenkins"
    jenkins_http_port: "8080"
    jenkins_admin_username: "admin"
    jenkins_admin_password: "admin"
    jenkins_jar_location: "/opt/jenkins-cli.jar"
    jenkins_plugins:
      - "ldap"
      - "exclusive-execution-plugin"
    jenkins_plugins_install_dependencies: "yes"
    jenkins_plugins_state: "present"
    jenkins_version: "2.138"
```

```
TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] *****************************************************************************************
changed: [] => (item=ldap)
changed: [] => (item=exclusive-execution-plugin)
```
