### ISSUE TITLE
Way to install jenkins under a different user ?

### ISSUE THREAD

**Issue by lmarecha** [geerlingguy/ansible-role-jenkins#239]
By default it use jenkins:jenkins to install and run the services.
Is there a way to change the credential to a custom one by using one variable ?
I tried to set as in the post #193 but they were ignored.
Tried by just setting:
```
    jenkins_process_user: <user>
    jenkins_process_group: <group>
```
and also with full options with same results
```
vars:
    jenkins_hostname: <hostname>
    jenkins_http_port: 8080
    jenkins_admin_username: <user>
    jenkins_admin_password: <pass>
    jenkins_plugin_timeout: 120
    jenkins_connection_delay: 5
    jenkins_connection_retries: 60
    jenkins_process_user: <user>
    jenkins_process_group: <group>
    jenkins_init_changes:
      - option: "JENKINS_USER"
        value: <user>
    jenkins_plugins:
      - token-macro
      - build-pipeline-plugin
      - timestamper
      - gradle
    jenkins_plugins_install_dependencies: "yes"
    jenkins_plugins_state: "present"
    jenkins_version: "2.144"

  roles:
    - role: geerlingguy.jenkins
      become: yes
      tag: instjenkins
```

Which give me in the /etc/sysconfig/jenkins

```
# Unix user account that runs the Jenkins daemon
# Be careful when you change this, as you need to update
# permissions of $JENKINS_HOME and /var/log/jenkins.
#
JENKINS_USER="jenkins"
JENKINS_USER="$JENKINS_USER <user>"
```
