### ISSUE TITLE
Plugins not from jenkins update center

### ISSUE THREAD

**Issue by ludicruz** [geerlingguy/ansible-role-jenkins#24]
We have to pull a plugin from a non-jenkins site and and would like to be able to use a url to pull down the plugin. What are your thoughts? This ability works fine:

```
jenkins_plugins:
  - ansible
  - ansicolor
  - name: some-plugin
    url: https://somesite.invalid/downloads/some-plugin.jpi
```

this works fine with 1.9.1 in the tasks/plugins.yaml

```
- name: Install Jenkins plugins.
  command: >
    java -jar {{ jenkins_jar_location }}
     -s http://{{ jenkins_hostname }}:8080/
     install-plugin {{ item.url if item.url is defined else item }}
    creates=/var/lib/jenkins/plugins/{{ item.name if item.name is defined else item }}.jpi
  with_items: jenkins_plugins
  notify: restart jenkins
```
