### ISSUE TITLE
Allow jenkins_java_options to be specified as a list

### ISSUE THREAD

**Issue by sf-nh** [geerlingguy/ansible-role-jenkins#276]
```
jenkins_java_options:
  - "-Djenkins.install.runSetupWizard=false"

  # 1.75G = 1792m
  # 1.5G  = 1536m
  - "-Xmx1536m"
  - "-Xms768m"

  - "-Djenkins.branch.WorkspaceLocatorImpl.PATH_MAX=0"

  # GC
  - "-XX:+UseG1GC"
  # Enable String Deduplication
  - "-XX:+UseStringDeduplication"
  # Enable Parallel Reference Processing
  - "-XX:+ParallelRefProcEnabled"
  # Ensure explicit System.gc() and metaspace resizing do not trigger a Full GC because this can trigger a very long pause
  - "-XX:+DisableExplicitGC"
```

is far clearer to a future maintainer than

```
jenkins_java_options: "-Djenkins.install.runSetupWizard=false -Xmx1536m -Xms768m -Djenkins.branch.WorkspaceLocatorImpl.PATH_MAX=0 -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC"
```

1. It permits easier reading of what options are being defined
1. It permits comments explaining _why_ they're being defined

**Comment by jimcox** [comment]
I think this change is causing an issue. When 'Modify variables in init file.' runs on fresh install, I am now getting this error:
```
failed: [jenkins-master-1] (item={'option': 'JENKINS_ARGS', 'value': '--prefix='}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "option": "JENKINS_ARGS",
        "value": "--prefix="
    },
```
The last line in my /etc/sysconfig/jenkins by default is 
```
JENKINS_ARGS=""
```
If I add a new line to the end of that file, the task will then succeed on replay with JENKINS_ARGS set to the expected value.

**Comment by mches** [comment]
You could use a [YAML multiline string](https://yaml-multiline.info/)
```yaml
jenkins_java_options: >-
  -Djenkins.install.runSetupWizard=false

# 1.75G = 1792m
# 1.5G  = 1536m
  -Xmx1536m
  -Xms768m

  -Djenkins.branch.WorkspaceLocatorImpl.PATH_MAX=0

# GC
  -XX:+UseG1GC
# Enable String Deduplication
  -XX:+UseStringDeduplication
# Enable Parallel Reference Processing
  -XX:+ParallelRefProcEnabled
# Ensure explicit System.gc() and metaspace resizing do not trigger a Full GC because this can trigger a very long pause
  -XX:+DisableExplicitGC
```

or a Jinja2 expression

```yaml
jenkins_java_options: "{{ jenkins_java_options_list | join(' ') }}"
jenkins_java_options_list:
  - "-Djenkins.install.runSetupWizard=false"

  # 1.75G = 1792m
  # 1.5G  = 1536m
  - "-Xmx1536m"
  - "-Xms768m"

  - "-Djenkins.branch.WorkspaceLocatorImpl.PATH_MAX=0"

  # GC
  - "-XX:+UseG1GC"
  # Enable String Deduplication
  - "-XX:+UseStringDeduplication"
  # Enable Parallel Reference Processing
  - "-XX:+ParallelRefProcEnabled"
  # Ensure explicit System.gc() and metaspace resizing do not trigger a Full GC because this can trigger a very long pause
  - "-XX:+DisableExplicitGC"
```
