### ISSUE TITLE
Allow configuration of jenkins proxy host and proxy port

### ISSUE THREAD

**Issue by rellaguo** [geerlingguy/ansible-role-jenkins#28]
When using the role to install jenkins behind proxy, jenkins server is OK, but jenkin plugins installation failed. To execute jenkins plugins install cli, /etc/default/jenkins should set JAVA_ARGS with -Dhttp.proxyHost=web-proxy.cce.hp.com -Dhttp.proxyPort=8080. 
I suppose use_proxy flag should be set. If use_proxy is true, settings.xml would execute task for insert JAVA_ARGS+=" -Dhttp.proxyHost={{ proxyHost }} -Dhttp.proxyPort={{ proxyPort }}" .

**Comment by vmwiz** [comment]
I'm using a groovy script for this, templated through ansible (Jenkins instance must be restarted after placing the script under /var/lib/jenkins/init.groovy.d/)

(works for Web and CLI)

```Groovy
import jenkins.model.*

def instance = Jenkins.getInstance()

final String name = "{{ jenkins_proxy_host }}"
final int port = {{ jenkins_proxy_port }}
final String userName = "{{ jenkins_proxy_user }}"
final String password = "{{ jenkins_proxy_pass }}"
final String noProxyHost = "{{ jenkins_proxy_exceptions }}"

final def pc = new hudson.ProxyConfiguration(name, port, userName, password, noProxyHost)
instance.proxy = pc
instance.save()
println "Proxy settings updated!"
```

**Comment by chrisweaver** [comment]
Using -D arguments isn't working for me, for Jenkins 2.x.  And the script from vmwiz works but it's not persistent. When I restart Jenkins the proxy settings are lost.  The only way I've found to get proxy working for Jenkins 2.x and make settings persistent is to create a $JENKINS_HOME/proxy.xml file.

**Comment by TimoEtzold** [comment]
just replace "instance.save()" with "pc.save()" and everything works as expected. 
The script can then be removed after it has run at least once (proxy.xml is created).

**Comment by haridsv** [comment]
@chrisweaver There is `save()` on the `hudson.ProxyConfiguration` class that also saves the config to the XML file. I tested it and verified it to be working.

**Comment by gtcdevop** [comment]
Try to set **Dhttp.proxyHost**  without protocol http://  only with host

**Comment by Mouzaffar** [comment]
> I'm using a groovy script for this, templated through ansible (Jenkins instance must be restarted after placing the script under /var/lib/jenkins/init.groovy.d/)
> 
> (works for Web and CLI)
> 
> ```groovy
> import jenkins.model.*
> 
> def instance = Jenkins.getInstance()
> 
> final String name = "{{ jenkins_proxy_host }}"
> final int port = {{ jenkins_proxy_port }}
> final String userName = "{{ jenkins_proxy_user }}"
> final String password = "{{ jenkins_proxy_pass }}"
> final String noProxyHost = "{{ jenkins_proxy_exceptions }}"
> 
> final def pc = new hudson.ProxyConfiguration(name, port, userName, password, noProxyHost)
> instance.proxy = pc
> instance.save()
> println "Proxy settings updated!"
> ```

You can use jenkins_script with templating the groovy script. dont have to restart jenkins with this solution. Something like this :
```
- name: Set proxy configuration
  jenkins_script:
    script: "{{ lookup('template', 'templates/proxy.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "{{ jenkins_home_url }}"
    validate_certs: no
  register: result_jenkins_proxy_conf
  failed_when: result_jenkins_proxy_conf.msg is defined and result_jenkins_proxy_conf.msg.find('script failed') != -1
```
