### ISSUE TITLE
restart jenkins handler does not run at the right time

### ISSUE THREAD

**Issue by mihailstoynov** [geerlingguy/ansible-role-jenkins#293]
Initially I was including this role in another role, that is part of a playbook.
The 'configure default users' handler runs because you flush all handlers in settings.yml.

But the `restart jenkins` handler does not run after your role is done. It waits until all tasks in the play are run.

I tried several things - `import_role`, `include_role` in my role, `import_role`, `include_role` in my play. I tried depending my role on your role. Still  `restart jenkins` handler does not run at the end of your role. It runs at the end of the whole play, which is incorrect.
(My role is basically a lot of `include_role`s)

Am I not seeing something. Is this an ansible issue? is this a special handler? How can I make sure this handler runs when you role is done with all its tasks?

The only thing that works is doing this:
```
- name: install and setup jenkins
  import_role:
    name: geerlingguy.jenkins

- name: Trigger handlers because geerlingguy.jenkins has a 'restart jenkins' handler that hasn't run
  meta: flush_handlers
```
