### ISSUE TITLE
plugin dependency not installed, even with jenkins_plugins_install_dependencies: true

### ISSUE THREAD

**Issue by timblaktu** [geerlingguy/ansible-role-jenkins#299]
With

```
- jenkins_plugins:
  - name: configuration-as-code                                                                                                                                                 
    version: "1.41"
- jenkins_plugins_install_dependencies: true
- jenkins_plugins_state: present
```

this role does not install snakeyaml-api, a dependency required by configuration-as-code, and I see:

"Failed to load CasC plugin (1.41)... Plugin is missing: snakeyml-api (1.26.1)"

error in "Manage Plugins".

When I explicitly include the versioned dependency:

```
- jenkins_plugins:                                                                                                                                                            
  - name: configuration-as-code                                                                                                                                                 
    version: "1.41"                                                                                                                                                           
  - name: snakeyaml-api                                                                                                                                                        
    version: "1.26.1"
- jenkins_plugins_install_dependencies: true
- jenkins_plugins_state: present
```

It of course installs the dependency and the error goes away.

I wasn't sure if this was a problem with this ansible role, or if the configuration-as-code plugin wasn't reporting it's deps properly.

Controller is Debian Stretch using ansible 2.9.2, ansible-role-jenkins version 4.3.0
Controlled machine is Debian Buster.
