### ISSUE TITLE
Installation on Debian croaks

### ISSUE THREAD

**Issue by amotl** [geerlingguy/ansible-role-jenkins#339]
Dear Jeff,

first things first: Thanks a stack for conceiving this excellent role for Ansible.

We just gave it a stab to apply it to one of our machines running Ubuntu 20.04 LTS by means of a snippet like:
```yaml
- name: Install Jenkins
  import_role:
    name: geerlingguy.jenkins
  vars:
    jenkins_prefer_lts: true
```

However, this fails:
```
Failed to update apt cache: E:The repository 'https://pkg.jenkins.io/debian-stable binary/ Release' does not have a Release file.
```

Maybe it is related to #334 in any way and could be resolved by applying #335 already?

With kind regards,
Andreas.
