### ISSUE TITLE
Can't find "{{ jenkins_java_options_env_var }}" in defaults

### ISSUE THREAD

**Issue by gadzillos** [geerlingguy/ansible-role-jenkins#341]
In git history, it was hardcoded as  ```"JENKINS_JAVA_OPTIONS"``` but now it is inconvenient where ```jenkins_java_options_env_var``` is located.

defaults:
```
jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
```

Maybe I just can't find it.
