### ISSUE TITLE
Port Changes and other defaults cannot be over ridden with the latest release.

### ISSUE THREAD

**Issue by jlombardo29** [geerlingguy/ansible-role-jenkins#351]
With the release of 2.332.1 there have been some changes to how Jenkins looks for overrides. 

https://www.jenkins.io/doc/book/system-administration/systemd-services/

TL:DR
SystemD is the new standard so the defaults file isn't working as it used to.

**Comment by geerlingguy** [comment]
It looks like in CI I'm also getting some failures, like:

```
failed: [instance] (item=ghprb) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "details": "HTTP Error 401: Unauthorized", "item": "ghprb", "msg": "Cannot get CSRF"}
```

**Comment by impca** [comment]
This needs some polishing (use all vars in teplate), but it should work:
```
- name: Create override directory
  file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory

- name: Add overrides
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    mode: 0644
```

And then in your templates/override.conf.j2 add all your required options:
```
[Unit]
Description=My Jenkins Controller

[Service]
# Add JVM configuration options
Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false "

# Arbitrary additional arguments to pass to Jenkins.
Environment="JENKINS_OPTS=--prefix={{ jenkins_url_prefix }} --javaHome=/opt/jdk-11"
```
