### ISSUE TITLE
Can not set specific jenkins version when use jenkins_prefer_lts: true 

### ISSUE THREAD

**Issue by patsevanton** [geerlingguy/ansible-role-jenkins#359]
Hello! Thanks for role jenkins!
Can not set specific jenkins version when use jenkins_prefer_lts: true.
If i set only  `jenkins_prefer_lts: true`, then installed latest lts jenkins version from debian-stable repository.

If i set only  `jenkins_prefer_lts: true` and `jenkins_version: "2.346.2"`, then try install jenkins version general jenkins repository.

For example:
Inventory
```
all:
  children:
    jenkins:
      hosts:
        "jenkins":
          ansible_host: "IP"
  vars:
    jenkins_prefer_lts: true
    jenkins_version: "2.346.2"
    jenkins_external_url: "https://jenkins.IP.sslip.io"

    jenkins_admin_password: password
    jenkins_hostname: "jenkins.IP.sslip.io"
```

Short Playbook
```
- name: "Deploy java, jenkins, letsencrypt, nginx"
  hosts: jenkins
  become: true
  roles:
    - role: robertdebock.java
    - role: geerlingguy.jenkins
```

output
```
TASK [geerlingguy.jenkins : Download specific Jenkins version.] 
fatal: [jenkins]: FAILED! => changed=false 
  dest: /tmp/jenkins_2.346.2_all.deb
  elapsed: 1
  msg: Request failed
  response: 'HTTP Error 404: Not Found'
  status_code: 404
  url: https://pkg.jenkins.io/debian/binary/jenkins_2.346.2_all.deb
```

Debian Repository have only [jenkins_2.346_all.deb](https://mirrors.jenkins.io/debian/jenkins_2.346_all.deb)

Debian LTS have https://mirrors.jenkins.io/debian-stable/jenkins_2.346.2_all.deb
