### ISSUE TITLE
Incorrect Regex to replace existing values?

### ISSUE THREAD

**Issue by prabjohns-atex** [geerlingguy/ansible-role-jenkins#386]
In Settings.yml

```
- name: Modify variables in init file.
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^Environment="{{ item.option }}='
    regexp: '^Environment="{{ item.option }} '
    line: 'Environment="{{ item.option }}={{ item.value }}"'
    state: present
    mode: 0644
  with_items: "{{ jenkins_init_changes }}"
  register: jenkins_init_prefix
```
The RegExp looks for a space after the option name - is this correct ?

I ended up with duplicated rows for JENKINS_PORT when I changed it from 8080.
