### ISSUE TITLE
Unable to setup jenkins on a newly provisioned server until dns propogates

### ISSUE THREAD

**Issue by frob** [geerlingguy/ansible-role-jenkins#45]
I was just running this on a dynamic DO inventory on a brand new server and it was hanging on the task to make jenkins start at boot. This is because jenkins was being curled against what will ultimately be its final url, but it doesn't work because DNS isn't propagated. I was able to fake it by setting up my host file before setting up jenkins. Is there a better way? Here is my task for faking my host file.

```yaml
  - name: "Build hosts file"
    lineinfile:
      dest: /etc/hosts
      regexp: ci\.example\.com
      line: "127.0.0.1 ci.example.com"
      state: present
```
