### ISSUE TITLE
selinux python bindings and java installation issue

### ISSUE THREAD

**Issue by mlushpenko** [geerlingguy/ansible-role-jenkins#62]
Greetings,

during the test on centos/6 vagrant box that runs on VirtualBox on Windows7, I got such error at 

> TASK [ansible-role-jenkins : Ensure URL prefix is present in Jenkins config.]

`fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}`

Probably one more task shall be added to setup-RedHat.yml:
```
- name: install selinux bindings 
  yum: name=libselinux-python state=present
```

Or dependencies task must be updated:
```
- name: Ensure dependencies are installed.
  yum: pkg={{item}} state=installed
  with_items:
    - curl
    - libselinux-python
```

Also I had an issue with java at 

> TASK [ansible-role-java-master : include] **************************************
included: /vagrant/ansible-role-java-master/tasks/setup-RedHat.yml for localhost

> TASK [ansible-role-java-master : Ensure Java is installed.]

`failed: [localhost] (item=[u'java-1.7.0-openjdk']) => {"changed": true, "failed": true, "item": ["java-1.7.0-openjdk"], "msg": "You need to be root to perform this command.\n", "rc": 1, "results": ["Loaded plugins: fastestmirror, security\n"]}
`

When I switched to root user the error disappeared, so I guess I have to add `become: yes` to some tasks or to the entire play, right?

I am not sure it can be considered as an issue, maybe more like a suggestion for improvement.

**Comment by geerlingguy** [comment]
@mlushpenko - Concerning play as the root user—yes, you can either run entire playbook as root, or use `become: yes` when you pass in the `geerlingguy.jenkins` role:

```yaml
---
- hosts: all
  roles:
    - name: geerlingguy.jenkins
      become: yes
```

For the other issue, I'd rather that be something done in the upstream playbook instead of inside this particular role, since it's platform/OS-specific and the bindings don't necessarily need to be present depending on your particular environment.
